---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

- name: Copy the code from repository
  git: repo={{ repository }} dest={{ tmp_path }}

- name: Copy the payload bits to the virtual host path
  shell: cp -Rf {{ tmp_path }}/dist/* {{ web_path }}
